'use client';
import { useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowUp, Mic, Plus, FileText, ImageIcon, X } from 'lucide-react';
import { useNemorra } from '@/components/app-provider';
import { SampleModal } from '@/components/modals/sample-modal';
export function UploadComposer({ onTeach, onListen }: { onTeach?: () => void; onListen?: () => void }) {
 const [text, setText] = useState(''); const [sample, setSample] = useState(false); const [menu, setMenu] = useState(false); const [fileName, setFileName] = useState('');
 const file = useRef<HTMLInputElement>(null); const router = useRouter(); const { setNotes, setTopic, setDraft } = useNemorra();
 const submit = () => { if (!text.trim() && !fileName) return; if (onTeach) { onTeach(); return; } setNotes(text.trim()); setTopic(fileName || 'My learning session'); setDraft(''); router.push('/teach'); };
 return <><div className="upload-box"><textarea aria-label={onTeach ? 'Your explanation' : 'Learning notes'} placeholder={onTeach ? 'Teach me in your own words...' : 'Add your notes, pdf, image...'} rows={1} value={text} onChange={(e) => { setText(e.target.value); e.target.style.height = 'auto'; e.target.style.height = `${Math.min(e.target.scrollHeight, 140)}px`; }} onKeyDown={(e) => { if (e.nativeEvent.isComposing || e.keyCode === 229) return; if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); submit(); } }} />{fileName && <div className="attachment-label"><FileText size={15}/><span className="truncate">{fileName}</span><button aria-label="Remove attachment" onClick={() => setFileName('')}><X size={16}/></button></div>}<div className="upload-controls"><button className="icon-button outlined" aria-label="Add attachment" aria-expanded={menu} onClick={() => setMenu(!menu)}><Plus size={25} style={{transform: menu ? 'rotate(45deg)' : undefined}} strokeWidth={1.5}/></button><div className="flex items-center gap-2"><button className="pill-button" onClick={() => setSample(true)}>Try a sample</button><button className="icon-button" aria-label="Start practice microphone" onClick={() => { if(onListen) onListen(); else router.push('/teach?listen=1'); }}><Mic size={24} strokeWidth={1.5}/></button><button className="icon-button solid" aria-label="Start learning from notes" disabled={!text.trim() && !fileName} onClick={submit}><ArrowUp size={26} strokeWidth={1.5}/></button></div></div>{menu && <div className="attachment-menu"><p className="quiet-note">Preview only · files aren&apos;t processed</p><button onClick={() => { if(file.current) { file.current.accept = '.pdf,.txt'; file.current.click(); } setMenu(false); }}><FileText size={19}/> Add a document</button><button onClick={() => { if(file.current) { file.current.accept = 'image/*'; file.current.click(); } setMenu(false); }}><ImageIcon size={19}/> Add an image</button></div>}<input ref={file} type="file" className="sr-only" tabIndex={-1} onChange={(e) => { const picked = e.target.files?.[0]; if(picked) setFileName(picked.name); e.target.value = ''; }}/></div><SampleModal open={sample} onClose={() => setSample(false)}/></>;
}
