'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, ArrowUp, ImagePlus, X, Check } from 'lucide-react';
import { motion } from 'motion/react';
import { PageTransition } from '@/components/page-transition';
import { useNemorra } from '@/components/app-provider';
import { NemorraLoader } from '@/components/loaders/nemorra-loader';
import { ScoreRing, ConceptDots } from '@/components/recordings/recording-list';
export function WriteScreen() {
 const { draft, setDraft, topic } = useNemorra(); const [file, setFile] = useState(''); const [stage,setStage] = useState<'write'|'thinking'|'done'>('write'); const input = useRef<HTMLInputElement>(null);
 useEffect(() => { if(stage !== 'thinking') return; const timer=setTimeout(() => setStage('done'),1700); return () => clearTimeout(timer); },[stage]);
 return <PageTransition><div className="flow-top"><Link href="/teach" className="icon-button outlined" aria-label="Back to Teach"><ArrowLeft size={19}/></Link><div className="flow-steps"><Check size={15}/><span>Teach</span><span className="flow-line"/><span className="current">Write</span><span className="flow-line"/><span>Recall</span></div></div><h1 className="page-title">Write</h1><p className="page-subtitle mt-2">Put what you remember into words.</p>{stage === 'write' ? <><div className="writing-box"><textarea aria-label="What you remember" value={draft} placeholder="No perfect sentences needed. Just you, your memory, and a blank page..." maxLength={12000} onChange={(e) => {setDraft(e.target.value);e.target.style.height='auto';e.target.style.height=`${Math.max(290,e.target.scrollHeight)}px`;}}/>{file && <div className="attachment-label px-5"><ImagePlus size={18}/><span className="truncate">{file}</span><button aria-label="Remove handwriting" onClick={() => setFile('')}><X size={17}/></button></div>}<div className="writing-toolbar"><button className="icon-button" aria-label="Add handwritten image" onClick={() => input.current?.click()}><ImagePlus size={22}/></button><span className="quiet-note">{draft.length.toLocaleString()} characters</span><button className="icon-button solid" disabled={!draft.trim() && !file} aria-label="Submit writing" onClick={() => setStage('thinking')}><ArrowUp size={23}/></button></div></div><input ref={input} className="sr-only" tabIndex={-1} type="file" accept="image/*" onChange={(e) => {setFile(e.target.files?.[0]?.name || '');e.target.value='';}}/><p className="quiet-note mt-4 text-center">{file ? 'Handwriting preview only. Your image will not be processed.' : 'Take your time. Remembering is the learning.'}</p><p className="quiet-note mt-8 text-center">Practicing: {topic}</p></> : stage === 'thinking' ? <div className="py-20"><NemorraLoader label="Seeing what stuck..."/></div> : <motion.div className="feedback-panel" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}><ScoreRing score={91} size={150}/><div><h2 className="text-3xl font-semibold tracking-tight">Great recall.</h2><p className="page-subtitle mt-2">8 / 9 concepts remembered</p><div className="flex justify-center"><ConceptDots total={9} filled={8}/></div></div><p className="quiet-note">Example score · your writing hasn&apos;t been evaluated.</p><Link className="primary-button w-full" href="/results">See what stuck <ArrowRight size={19}/></Link><button className="pill-button" onClick={() => setStage('write')}>Keep writing</button></motion.div>}</PageTransition>;
}
