'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Download, Pencil, Trash2 } from 'lucide-react';
import { PageTransition } from '@/components/page-transition';
import { Mascot } from '@/components/mascot/mascot';
import { useNemorra } from '@/components/app-provider';
import { Modal } from '@/components/modals/modal';
export function AccountScreen() {
  const { profile, setProfile, calm, setCalm, records, exportData, reset } = useNemorra();
  const [edit, setEdit] = useState(false); const [name, setName] = useState(profile.name); const [confirm, setConfirm] = useState(false);
  return <PageTransition><h1 className="page-title">Your corner.</h1><p className="page-subtitle mt-2">A little space for you and your learning.</p><section className="mt-8 flex items-center justify-between"><div className="flex items-center gap-4"><Mascot state="happy" className="size-20 [&_img]:size-full [&_img]:object-contain"/><div><h2 className="text-xl font-semibold tracking-tight">{profile.name}</h2><p className="quiet-note">Local profile · no sign-in</p></div></div><button aria-label="Edit local profile" className="icon-button outlined" onClick={() => { setName(profile.name); setEdit(true); }}><Pencil size={17}/></button></section>
    <section className="account-card mt-8"><h2 className="text-xl font-semibold">Your device, your learning.</h2><p className="page-subtitle mt-3">{records.length} saved {records.length === 1 ? 'session' : 'sessions'}</p><p className="quiet-note mt-3">The latest 100 completed sessions, drafts, and preferences are saved in this browser. There is no cloud backup or cross-device sync. Clearing site data removes them. Other people using this browser can access them.</p><div className="mt-5 flex flex-col gap-3"><button className="pill-button" onClick={exportData}><Download size={18}/>Export learning data</button><button className="pill-button" onClick={() => setConfirm(true)}><Trash2 size={18}/>Delete local data</button></div></section>
    <section className="mt-8"><h2 className="text-xl font-semibold">Settings</h2><div className="setting-row"><div><p>Quiet motion</p><p className="quiet-note mt-1">A little less movement.</p></div><button className="toggle" role="switch" aria-label="Quiet motion" aria-checked={calm} onClick={() => setCalm(!calm)}><span/></button></div></section>
    <section className="account-card mt-7"><h2 className="text-lg font-semibold">About your data</h2><p className="quiet-note mt-3">Notes, uploaded documents, and answers are sent to Gemini through Vercel AI Gateway only when you request processing. Files are not saved by Nemorra; extracted text is saved on this device. Optional dictation may use your browser provider&apos;s remote speech service.</p><p className="quiet-note mt-3">AI feedback can be wrong. Check important facts against your source. No subscription or payment is enabled. AI service usage is separate from v0 credits.</p><p className="quiet-note mt-3">This local-first version has no account-based abuse protection. Before sharing it publicly, set provider budget limits and add authenticated usage controls.</p></section><Link href="/onboarding" className="pill-button mt-7">How Nemorra works</Link>
    <Modal open={edit} onClose={() => setEdit(false)} title="Make yourself at home"><form className="flex flex-col gap-4" onSubmit={e => { e.preventDefault(); if (name.trim()) { setProfile({ name: name.trim() }); setEdit(false); } }}><label htmlFor="learner-name" className="text-sm">Your name</label><input id="learner-name" className="profile-input" autoComplete="nickname" maxLength={80} required value={name} onChange={e => setName(e.target.value)}/><button className="primary-button" disabled={!name.trim()}>Save profile</button></form></Modal>
    <Modal open={confirm} onClose={() => setConfirm(false)} title="Start with a clean page?"><p className="page-subtitle">This deletes all Nemorra sessions, notes, drafts, and preferences from this browser. Export a copy first if you want to keep them.</p><button className="primary-button" onClick={() => { reset(); setConfirm(false); }}>Delete all local data</button><button className="pill-button" onClick={() => setConfirm(false)}>Keep my learning</button></Modal></PageTransition>;
}
