'use client';
import { useState } from 'react';
import { motion } from 'motion/react';
import { MoreVertical, Pin, Trash2, ArrowRight } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { useNemorra } from '@/components/app-provider';
import { Modal } from '@/components/modals/modal';
import { type Recording } from '@/lib/mock-data';
export function ScoreRing({ score, size = 62 }: { score: number; size?: number }) {
 return <div className="score-ring" style={{ width: size, height: size }} aria-label={`${score}% recall`}><svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="32" r="28" fill="none" stroke="var(--border)" strokeWidth="5"/><motion.circle cx="32" cy="32" r="28" fill="none" stroke="var(--foreground)" strokeWidth="5" strokeLinecap="butt" initial={{ pathLength: 0 }} whileInView={{ pathLength: score / 100 }} viewport={{ once: true }} transition={{ duration: 1.2, ease: 'easeOut' }}/></svg><span>{score}%</span></div>;
}
export function ConceptDots({ total, filled }: { total: number; filled: number }) {
 return <div className="concept-dots" aria-label={`${filled} of ${total} concepts remembered`}>{Array.from({length: total}, (_, i) => <motion.span key={i} initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }} transition={{ delay: i * .035 }} className={`concept-dot ${i >= filled ? 'empty' : ''}`} />)}</div>;
}
export function RecordingList({ query = '' }: { query?: string }) {
 const { records, setRecords, setTopic } = useNemorra(); const [menu, setMenu] = useState<string | null>(null); const [selected, setSelected] = useState<Recording | null>(null); const router = useRouter();
 const filtered = [...records].sort((a,b) => Number(!!b.pinned) - Number(!!a.pinned)).filter(r => r.title.toLowerCase().includes(query.toLowerCase()));
 return <><div className="flex flex-col gap-2.5">{filtered.map(record => <motion.article key={record.id} className="recording-card" initial={{opacity:0,y:8}} whileInView={{opacity:1,y:0}} viewport={{once:true}} whileTap={{scale:.992}}><button className="recording-main" onClick={() => setSelected(record)} aria-label={`Review ${record.title}, ${record.score}% recall`}><ScoreRing score={record.score}/><div className="min-w-0"><h3 className="recording-title">{record.pinned && <Pin size={12} className="mr-1 inline"/>}{record.title}</h3><p className="recording-meta">{record.concepts} concepts <span className="px-1.5">·</span> {record.date}</p><ConceptDots total={record.concepts + 2} filled={record.concepts}/></div></button><button className="icon-button recording-menu-button" aria-label={`Options for ${record.title}`} aria-expanded={menu === record.id} onClick={() => setMenu(menu === record.id ? null : record.id)}><MoreVertical size={21}/></button>{menu === record.id && <div className="pop-menu"><button onClick={() => { setRecords(rows => rows.map(r => r.id === record.id ? {...r,pinned: !r.pinned} : r)); setMenu(null); }}><Pin size={16}/>{record.pinned ? 'Unpin' : 'Pin recording'}</button><button onClick={() => { setRecords(rows => rows.filter(r => r.id !== record.id)); setMenu(null); }}><Trash2 size={16}/>Remove recording</button></div>}</motion.article>)}{!filtered.length && <p className="quiet-note py-8 text-center">{query ? 'No recordings match your search.' : 'A fresh page. Start your first learning session above.'}</p>}</div><Modal open={!!selected} onClose={() => setSelected(null)} title={selected?.title || 'Recording'}>{selected && <><div className="flex items-center gap-5"><ScoreRing score={selected.score} size={82}/><div><h3 className="text-lg font-semibold">Beautifully remembered.</h3><p className="quiet-note">{selected.concepts} concepts · {selected.date}</p></div></div><p className="quiet-note">This is a sample recording. Try another practice session to explore the learning flow.</p><button className="primary-button" onClick={() => { setTopic(selected.title); setSelected(null); router.push('/teach'); }}>Practice again <ArrowRight size={18}/></button></>}</Modal></>;
}
