'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Square, BookOpen } from 'lucide-react';
import { AnimatePresence, motion } from 'motion/react';
import { PageTransition } from '@/components/page-transition';
import { Mascot } from '@/components/mascot/mascot';
import { UploadComposer } from '@/components/upload/upload-composer';
import { useNemorra } from '@/components/app-provider';
import { Modal } from '@/components/modals/modal';
import { samplePassage } from '@/lib/mock-data';
export function TeachScreen() {
 const [stage, setStage] = useState<'ready'|'listening'|'thinking'|'happy'>('ready'); const [seconds, setSeconds] = useState(0); const [source, setSource] = useState(false); const { notes, topic } = useNemorra();
 useEffect(() => { if(new URLSearchParams(window.location.search).get('listen') === '1') setStage('listening'); },[]);
 useEffect(() => { if(stage !== 'listening') return; const timer = setInterval(() => setSeconds(s => s+1),1000); return () => clearInterval(timer); },[stage]);
 useEffect(() => { if(stage !== 'thinking') return; const timer = setTimeout(() => setStage('happy'),1800); return () => clearTimeout(timer); },[stage]);
 return <PageTransition className="teach-page"><div className="flow-top"><Link href="/" className="icon-button outlined" aria-label="Back home"><ArrowLeft size={19}/></Link><div className="flow-steps"><span className="current">Teach</span><span className="flow-line"/><span>Write</span><span className="flow-line"/><span>Recall</span></div><button className="icon-button" aria-label="Review learning material" onClick={() => setSource(true)}><BookOpen size={22}/></button></div><header><h1 className="page-title">Teach</h1><p className="page-subtitle mt-2">I&apos;m listening. Teach me what you just learned.</p></header><AnimatePresence mode="wait">{stage === 'ready' || stage === 'listening' ? <motion.div key="listening" className="teach-stage" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="teach-status" aria-live="polite">{stage === 'listening' && <><div className="waveform" aria-hidden="true">{Array.from({length:5},(_,i)=><i key={i}/>)}</div><p className="page-subtitle">I&apos;m listening...</p><p className="quiet-note">Practice mic · {Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</p></>}</div><Mascot state="listening" priority className="teach-mascot" audioLevel={stage === 'listening' ? (seconds % 4) / 4 : 0}/></motion.div> : <motion.div key={stage} className="feedback-panel" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0}}><Mascot state={stage} className="feedback-mascot"/><div><h2 className="text-2xl font-semibold tracking-tight">{stage === 'thinking' ? 'Let me think about that...' : 'You made that make sense.'}</h2><p className="page-subtitle mt-3">{stage === 'thinking' ? 'Connecting the little pieces.' : 'Now, let’s see what stays when you put it into words.'}</p></div>{stage === 'happy' && <><p className="quiet-note">Demo feedback · no audio was recorded or analyzed.</p><Link href="/write" className="primary-button w-full">Let&apos;s write <ArrowRight size={19}/></Link><button className="pill-button" onClick={() => {setSeconds(0);setStage('ready');}}>Practice again</button></>}</motion.div>}</AnimatePresence>{stage === 'ready' && <UploadComposer onTeach={() => setStage('thinking')} onListen={() => {setSeconds(0);setStage('listening');}}/>}{stage === 'listening' && <div className="flex flex-col items-center gap-3"><button className="primary-button w-full" onClick={() => setStage('thinking')}><Square size={15} fill="currentColor"/>Done teaching</button><p className="quiet-note text-center">Simulated listening. Your microphone is not used.</p></div>}<Modal open={source} onClose={() => setSource(false)} title={topic}><p className="quiet-note">Read it once, then explain it in your own words.</p><p className="sample-passage">{notes || samplePassage}</p><button className="primary-button" onClick={() => setSource(false)}>I&apos;m ready</button></Modal></PageTransition>;
}
